# Generated by Django 5.1.1 on 2025-04-22 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Created timestamp')),
                ('updated_timestamp', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated timestamp')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagen')),
                ('min_weight_allowed', models.PositiveSmallIntegerField(verbose_name='Peso mínimo permitido')),
                ('price_by_weight_unit', models.FloatField(null=True, blank=True, verbose_name='Precio por libra')),
                ('time_to_delivery', models.CharField(max_length=100, verbose_name='Tiempo para llegada de envío')),
            ],
            options={
                'verbose_name': 'Tipo de envío',
                'verbose_name_plural': 'Tipos de envíos',
            },
        ),
    ]
