# Generated by Django 5.1.1 on 2025-05-06 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_app', '0002_shippingtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='in_cuba',
            field=models.BooleanField(default=False, verbose_name='En Cuba'),
        ),
    ]
