# Generated by Django 5.1.1 on 2025-06-22 00:39

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0003_category_in_cuba"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_timestamp",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created timestamp"
                    ),
                ),
                (
                    "updated_timestamp",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated timestamp"
                    ),
                ),
                (
                    "weight",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=0)
                        ],
                        verbose_name="Peso",
                    ),
                ),
                (
                    "subtotal_without_shipping",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=0)
                        ],
                        verbose_name="Precio sin envío",
                    ),
                ),
                (
                    "total_with_shipping",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(limit_value=0)
                        ],
                        verbose_name="Precio total con envío",
                    ),
                ),
                (
                    "generated_whatsapp_message",
                    models.TextField(verbose_name="Mensaje de whatsapp generado"),
                ),
                (
                    "shipping_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="business_app.shippingtype",
                        verbose_name="Tipo de envío",
                    ),
                ),
            ],
            options={
                "verbose_name": "Orden de compra",
                "verbose_name_plural": "Órdenes de compra",
            },
        ),
    ]
