# Generated by Django 5.1.1 on 2025-07-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("business_app", "0004_sellorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="priced_per_unit",
            field=models.BooleanField(
                default=False, verbose_name="Precio fijo por unidad"
            ),
        ),
    ]
