
# version: '3.8'  # Versión de Docker Compose

services:
  postgres:
    container_name: mi_isla_postgres
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_REMOTE_NAME}
      POSTGRES_USER: ${DB_REMOTE_USER}
      POSTGRES_PASSWORD: ${DB_REMOTE_PASSWORD}
    ports:
      - "${DB_REMOTE_PORT}:5432"
    volumes:
      - postgres_data_volume_mi_isla:/var/lib/postgresql/data
    restart: always  # Opcional: reinicia el contenedor si falla

  redis:
    container_name: mi_isla_redis
    image: redis:latest
    restart: always
    ports:
      - ${REDIS_PORT}:6379

volumes:
  postgres_data_volume_mi_isla: {}  # Define el volumen